import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Fitness Application',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
